FROM influxdb:latest
# Variabili di ambiente per la configurazione di InfluxDB
ENV INFLUXDB_DB=mydb
ENV INFLUXDB_ADMIN_USER=admin
ENV INFLUXDB_ADMIN_PASSWORD=adminpassword
ENV INFLUXDB_USER=myuser
ENV INFLUXDB_USER_PASSWORD=mypassword
VOLUME ["./db"]
EXPOSE 8086
CMD ["influxd"]
#r_4PwE4Bkhjq7Unn81tNWOwV23vTrpAj3uUxuvmG0s1-W_CBkHzt0lwk8iBrNzFIQVWaovUPBBfNCZ7_bX2MMw==

#new token: KQyL5kf_jbtDsYXh5qDB8Krj_DHPpCBFXrhA2uptgux_VrsWHeQByGSG66-2RB1t72K-vBjxKCXRxjNSQfCTrw==